parameters:
    J1:
        encoder_cpt: 1.0
        loadcell: 2.0
        cacca: 3.0
        ROM_Min: 0.0
        ROM_Max: 0.0

    J2:
        encoder_cpt: 1.0
        loadcell: 2.0
        cacca: 3.0
        ROM_Min: 0.0
        ROM_Max: 0.0

    J3:
        encoder_cpt: 1.0
        loadcell: 2.0
        cacca: 3.0
        ROM_Min: 0.0
        ROM_Max: 0.0
